export const icons = {
    favIcon : "/assets/icons/favicon.svg",
    logo : "/assets/icons/logo.svg",
    closeIcon : "/assets/icons/close.svg",
    eventProfile : "/assets/icons/profile-icon.svg",
    packageIcon : "/assets/icons/package.svg",
    packageIconBlack : "/assets/icons/package-black.svg",
    clockIcon : "/assets/icons/clock.svg",
    locationIcon : "/assets/icons/location.svg",
    angleDown : "/assets/icons/angle-down.svg",
    angleLeft: '/assets/icons/angle-left-solid.svg',
    angleRight: '/assets/icons/angle-right-solid.svg',
    editIcon : "/assets/icons/pencil-write.svg",
    removeIcon : "/assets/icons/trash.svg",
    displayIcon : "/assets/icons/eye-icon.svg",
    addIcon : "/assets/icons/add-icon.svg",
    profileIcon : "/assets/icons/profile-black.svg",
    caledarIcon: "/assets/icons/calendar.svg",
    deliberableIcon: "/assets/icons/shape.svg",
    arrowIcon: "/assets/icons/arrow.svg",
    imagePlacholder: "/assets/adminHome/image_placeholder.jpg",
} as const;